inveniosoftware/invenio-vocabularies

invenio_vocabularies/alembic/4f365fced43f_create_vocabularies_tables.py
invenio_vocabularies/alembic/8ff82dfb0be8_create_vocabularies_branch.py
invenio_vocabularies/contrib/affiliations/__init__.py
invenio_vocabularies/contrib/subjects/api.py
invenio_vocabularies/contrib/subjects/models.py
setup.py
tests/conftest.py
tests/test_alembic.py

closes inveniosoftware/invenio-rdm-records#355

355 alembic

---

invenio_vocabularies/cli.py

closes inveniosoftware/invenio-rdm-records#364

Languages: removed language import

---

invenio_vocabularies/contrib/affiliations/jsonschemas/affiliations/affilation-v1.0.0.json
invenio_vocabularies/records/api.py
invenio_vocabularies/records/jsonschemas/vocabularies/vocabulary-v1.0.0.json
tests/conftest.py
tests/mock_module/api.py
tests/mock_module/jsonschemas/records/record-v1.0.0.json

Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/356.

records: change schemas to use local URI scheme

---

invenio_vocabularies/records/mappings/v6/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/mappings/v7/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/services/service.py
invenio_vocabularies/version.py
setup.py
tests/resources/test_resources_get.py

* Partially closes https://github.com/inveniosoftware/invenio-app-rdm/issues/738
* Needs https://github.com/inveniosoftware/invenio-records-resources/pull/220

services: Overrides QueryStrParam

---

invenio_vocabularies/services/facets.py
setup.py
tests/services/conftest.py
tests/services/test_facets.py

closes https://github.com/inveniosoftware/invenio-vocabularies/issues/36

services: add facet labelling

---

invenio_vocabularies/services/facets/facets.py
invenio_vocabularies/version.py
tests/services/test_facets.py

facets: fix nested labelling on empty buckets

---

.gitignore
invenio_vocabularies/services/facets/labels.py
invenio_vocabularies/services/service.py
tests/conftest.py
tests/services/test_service.py

services: read many implemented and tested

---

invenio_vocabularies/alembic/6312f33645c1_create_affiliations_table.py
invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/affiliations/api.py
invenio_vocabularies/contrib/affiliations/config.py
invenio_vocabularies/contrib/affiliations/jsonschemas/__init__.py
invenio_vocabularies/contrib/affiliations/mappings/v6/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/mappings/v7/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/models.py
invenio_vocabularies/contrib/affiliations/schema.py
invenio_vocabularies/contrib/affiliations/services.py
invenio_vocabularies/records/mappings/v6/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/mappings/v7/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/pidprovider.py
invenio_vocabularies/records/systemfields/__init__.py
invenio_vocabularies/records/systemfields/pid.py
invenio_vocabularies/services/permissions.py
invenio_vocabularies/services/schema.py
setup.py
tests/contrib/affiliations/conftest.py
tests/contrib/affiliations/test_affiliations_api.py
tests/contrib/affiliations/test_affiliations_jsonschema.py
tests/contrib/affiliations/test_affiliations_schema.py
tests/contrib/affiliations/test_affiliations_service.py
tests/records/test_jsonschema.py

requires https://github.com/inveniosoftware/invenio-vocabularies/pull/49
partly closes https://github.com/inveniosoftware/invenio-rdm-records/issues/328

contrib: affiliations vocabulary

---

invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/affiliations/config.py
invenio_vocabularies/contrib/affiliations/mappings/v6/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/mappings/v7/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/resources.py
invenio_vocabularies/resources/resource.py
tests/conftest.py
tests/contrib/affiliations/conftest.py
tests/contrib/affiliations/test_affiliations_resource.py
tests/contrib/affiliations/test_affiliations_service.py

requires https://github.com/inveniosoftware/invenio-records-resources/pull/267
closes inveniosoftware/invenio-rdm-records#328

affiliations vocabulary resource layer

---

.github/workflows/pypi-publish.yml
babel.ini
invenio_vocabularies/translations/messages.pot
setup.cfg
setup.py

todo:
* create a new resource for this module in transifex
* push the .pot file to created resource on transifex

i18n: adds translation files/commands

---

invenio_vocabularies/config.py
invenio_vocabularies/contrib/affiliations/config.py
invenio_vocabularies/contrib/affiliations/schema.py
tests/contrib/affiliations/test_affiliations_schema.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/535

contrib: use new IdentifierSchema for affiliations identifiers

---

invenio_vocabularies/config.py
invenio_vocabularies/version.py

- requires https://github.com/inveniosoftware/marshmallow-utils/pull/43
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/962

contrib: update affiliations identifiers scheme structure

---

invenio_vocabularies/services/service.py
tests/services/test_service.py

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/760

services: update read_all

---

.gitignore
invenio_vocabularies/contrib/subjects/__init__.py
invenio_vocabularies/contrib/subjects/facets.py
invenio_vocabularies/version.py
tests/contrib/subjects/test_subjects_facets.py

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/68
- release: v0.8.1

subjects: label facets

---

invenio_vocabularies/contrib/names/mappings/v7/names/name-v1.0.0.json

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/113

names: add suggester to affiliations name

---

invenio_vocabularies/cli.py
invenio_vocabularies/config.py
invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/datastreams/__init__.py
invenio_vocabularies/datastreams/errors.py
invenio_vocabularies/datastreams/factories.py
invenio_vocabularies/datastreams/readers.py
invenio_vocabularies/datastreams/transformers.py
invenio_vocabularies/datastreams/writers.py
invenio_vocabularies/fixtures.py
setup.py
tests/contrib/names/test_names_api.py
tests/contrib/names/test_names_datastreams.py
tests/datastreams/conftest.py
tests/datastreams/test_readers.py
tests/datastreams/test_writers.py
tests/datastreams/vocabularies.yaml
tests/test_cli.py

- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/103
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/87
Sample command:
```
invenio vocabularies delete -v names -i crxej-zf213
```

cli: implement delete command

---

invenio_vocabularies/resources/resource.py
invenio_vocabularies/version.py
run-tests.sh
setup.py
tests/contrib/affiliations/test_affiliations_service.py
tests/contrib/subjects/test_subjects_service.py
tests/services/test_permissions.py
tests/services/test_service.py

- services: order methods to pass identity first
- release: v0.10.2

258 refactor service method parameters order

---

invenio_vocabularies/translations/de/LC_MESSAGES/messages.po
invenio_vocabularies/translations/messages.pot
setup.cfg

babel: set use fuzzy true

---

invenio_vocabularies/cli.py
invenio_vocabularies/datastreams/datastreams.py

closes https://github.com/inveniosoftware/invenio-vocabularies/issues/142

datastreams: feedback number of filtered entries

---

invenio_vocabularies/datastreams/__init__.py
invenio_vocabularies/datastreams/datastreams.py
invenio_vocabularies/datastreams/factories.py
invenio_vocabularies/datastreams/readers.py
invenio_vocabularies/datastreams/transformers.py
invenio_vocabularies/datastreams/writers.py
invenio_vocabularies/fixtures.py
tests/datastreams/conftest.py
tests/datastreams/test_fixtures.py
tests/resources/test_tasks_resources.py

datastreams: make base classes abstract

---

invenio_vocabularies/alembic/e1146238edd3_create_awards_table.py
invenio_vocabularies/config.py
invenio_vocabularies/contrib/awards/__init__.py
invenio_vocabularies/contrib/awards/api.py
invenio_vocabularies/contrib/awards/awards.py
invenio_vocabularies/contrib/awards/config.py
invenio_vocabularies/contrib/awards/jsonschemas/__init__.py
invenio_vocabularies/contrib/awards/jsonschemas/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/v6/__init__.py
invenio_vocabularies/contrib/awards/mappings/v6/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/v7/__init__.py
invenio_vocabularies/contrib/awards/mappings/v7/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/models.py
invenio_vocabularies/contrib/awards/resources.py
invenio_vocabularies/contrib/awards/schema.py
invenio_vocabularies/contrib/awards/services.py
tests/contrib/awards/conftest.py
tests/contrib/awards/test_awards_api.py
tests/contrib/awards/test_awards_jsonschema.py
tests/contrib/awards/test_awards_resource.py
tests/contrib/awards/test_awards_schema.py
tests/contrib/awards/test_awards_service.py
tests/test_alembic.py

This PR fixes https://github.com/inveniosoftware/invenio-vocabularies/issues/158

Awards vocabulary

---

invenio_vocabularies/cli.py
invenio_vocabularies/contrib/funders/datastreams.py
invenio_vocabularies/contrib/funders/facets.py
invenio_vocabularies/contrib/names/datastreams.py
tests/contrib/affiliations/conftest.py
tests/contrib/awards/conftest.py
tests/contrib/funders/conftest.py
tests/contrib/funders/test_funders_datastreams.py
tests/contrib/names/conftest.py
tests/contrib/names/test_names_datastreams.py
tests/contrib/subjects/conftest.py
tests/test_cli.py

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/318
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/931

global: rename registered services

---

invenio_vocabularies/contrib/awards/config.py
invenio_vocabularies/contrib/names/config.py
invenio_vocabularies/services/components.py
setup.py

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/172

Remove cmp

---

invenio_vocabularies/contrib/names/schema.py
invenio_vocabularies/contrib/subjects/schema.py
tests/contrib/subjects/test_subjects_schema.py

closes https://github.com/inveniosoftware/invenio-vocabularies/issues/98

contrib: add subject relation schema

---

invenio_vocabularies/contrib/awards/datastreams.py
invenio_vocabularies/contrib/awards/schema.py
invenio_vocabularies/contrib/funders/datastreams.py
invenio_vocabularies/contrib/funders/facets.py
invenio_vocabularies/contrib/funders/schema.py
setup.cfg
tests/contrib/awards/conftest.py
tests/contrib/awards/test_awards_api.py
tests/contrib/awards/test_awards_datastreams.py
tests/contrib/awards/test_awards_resource.py
tests/contrib/awards/test_awards_schema.py
tests/contrib/awards/test_awards_service.py
tests/contrib/funders/conftest.py
tests/contrib/funders/test_funders_api.py
tests/contrib/funders/test_funders_datastreams.py
tests/contrib/funders/test_funders_resource.py
tests/contrib/funders/test_funders_schema.py
tests/contrib/funders/test_funders_service.py

- vocabularies: fixed award/funder schema
- installation: fix old extras key
- contrib: fix funders/awards "pid" load/dump

Fix funding/awards PID key

---

invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/affiliations/mappings/v6/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/mappings/v7/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/awards/awards.py
invenio_vocabularies/contrib/awards/mappings/v6/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/v7/awards/award-v1.0.0.json
invenio_vocabularies/contrib/funders/funders.py
invenio_vocabularies/contrib/funders/mappings/v6/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/funders/mappings/v7/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/names/mappings/v6/names/name-v1.0.0.json
invenio_vocabularies/contrib/names/mappings/v7/names/name-v1.0.0.json
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/contrib/subjects/mappings/v6/subjects/subject-v1.0.0.json
invenio_vocabularies/contrib/subjects/mappings/v7/subjects/subject-v1.0.0.json
invenio_vocabularies/contrib/subjects/subjects.py
invenio_vocabularies/records/api.py
invenio_vocabularies/records/mappings/v6/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/mappings/v7/vocabularies/vocabulary-v1.0.0.json
tests/contrib/affiliations/test_affiliations_service.py
tests/contrib/awards/test_awards_service.py
tests/contrib/funders/test_funders_service.py
tests/contrib/names/test_names_service.py
tests/contrib/subjects/test_subjects_service.py
tests/services/test_service.py

- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/178

contrib: add indexed_at elasticsearch field to affiliations

---

invenio_vocabularies/__init__.py

**blocked** till this PR https://github.com/inveniosoftware/invenio-rdm-records/pull/952 is passing

release: v0.11.4

---

invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/awards/awards.py
invenio_vocabularies/contrib/funders/funders.py
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/contrib/subjects/subjects.py
invenio_vocabularies/services/service.py
setup.cfg
tests/contrib/affiliations/test_affiliations_service.py
tests/contrib/awards/test_awards_service.py
tests/contrib/funders/test_funders_service.py
tests/contrib/names/test_names_service.py
tests/contrib/subjects/test_subjects_service.py

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/332
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/190

services: add service id to config

---

babel.ini
invenio_vocabularies/contrib/awards/datastreams.py
invenio_vocabularies/translations/messages.pot

* remove jinja extensions
* adds fuzzy string true
* change f-string to format
* update .pot
related inveniosoftware/invenio-app-rdm#1664

i18n: extract messages

---

invenio_vocabularies/translations/de/LC_MESSAGES/messages.po

* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664

i18n: add german translations

---

invenio_vocabularies/contrib/affiliations/schema.py
invenio_vocabularies/contrib/funders/schema.py
invenio_vocabularies/contrib/subjects/schema.py
invenio_vocabularies/custom_fields/__init__.py
invenio_vocabularies/services/schema.py
tests/conftest.py
tests/custom_fields/test_custom_fields.py

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/368
- closes #205

service relation schemas generalization

---

invenio_vocabularies/contrib/awards/schema.py
invenio_vocabularies/contrib/funders/schema.py
invenio_vocabularies/contrib/names/schema.py

Ref: https://github.com/inveniosoftware/invenio-app-rdm/issues/1707

global: Fixes error messages.

---

.gitignore
invenio_vocabularies/records/systemfields/relations.py
invenio_vocabularies/services/custom_fields/__init__.py
invenio_vocabularies/services/custom_fields/vocabulary.py
tests/custom_fields/test_custom_fields.py

rename custom to custom_fields

---

invenio_vocabularies/services/custom_fields/vocabulary.py

cf: pass identity to options method

---

.gitignore
invenio_vocabularies/__init__.py
setup.cfg

release: v0.12.0

---

invenio_vocabularies/__init__.py
invenio_vocabularies/records/systemfields/relations.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1029

systemfields: make _fields a property instead of attribute

---

invenio_vocabularies/contrib/awards/datastreams.py
invenio_vocabularies/contrib/funders/datastreams.py
invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/datastreams/writers.py
tests/contrib/awards/test_awards_datastreams.py
tests/contrib/funders/test_funders_datastreams.py
tests/contrib/names/test_names_datastreams.py
tests/datastreams/test_writers.py

datastreams: contrib service writers state the service name

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v1.0.3

---

invenio_vocabularies/records/mappings/os-v1/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/mappings/os-v2/vocabularies/vocabulary-v1.0.0.json
invenio_vocabularies/records/mappings/v7/vocabularies/vocabulary-v1.0.0.json

mappings: add dynamic template for i18n titles and descriptions

---

invenio_vocabularies/resources/resource.py

- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1204

serializers: deprecate marshamllow JSON

---

invenio_vocabularies/contrib/funders/datastreams.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162

translations: remove redundant f-string

---

.github/workflows/tests.yml
MANIFEST.in
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/.eslintrc.yml
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/.prettierrc
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/index.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/package.json
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/AwardResults.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FunderDropdown.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.test.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingFieldItem.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingModal.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/NoAwardResults.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/index.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/index.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/index.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/index.js
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/i18next-scanner.config.js
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/i18next.js
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/messages/index.js
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/package.json
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/scripts/compileCatalog.js
invenio_vocabularies/assets/semantic-ui/translations/invenio_vocabularies/scripts/initCatalog.js
invenio_vocabularies/webpack.py
run-js-linter.sh
setup.cfg

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1276

assets: add UI contrib components

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v1.5.1

---

.github/workflows/tests.yml
CHANGES.rst
invenio_vocabularies/__init__.py
invenio_vocabularies/contrib/awards/schema.py

Closes https://github.com/zenodo/rdm-project/issues/229

awards schema: Add acronym

---

.github/workflows/tests.yml
invenio_vocabularies/services/custom_fields/vocabulary.py

* closes https://github.com/zenodo/who-rdm/issues/82

service: add sort option to load vocabs

---

.github/workflows/tests.yml
invenio_vocabularies/alembic/55a700f897b6_add_names_and_afiliations_pid_column.py
invenio_vocabularies/config.py
invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/affiliations/jsonschemas/affiliations/affiliation-v1.0.0.json
invenio_vocabularies/contrib/affiliations/schema.py
invenio_vocabularies/contrib/awards/datastreams.py
invenio_vocabularies/contrib/awards/jsonschemas/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/os-v1/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/os-v2/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/mappings/v7/awards/award-v1.0.0.json
invenio_vocabularies/contrib/awards/schema.py
invenio_vocabularies/contrib/awards/serializer.py
invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/contrib/names/jsonschemas/names/name-v1.0.0.json
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/contrib/names/schema.py
invenio_vocabularies/services/schema.py
run-tests.sh
tests/contrib/affiliations/test_affiliations_api.py
tests/contrib/affiliations/test_affiliations_jsonschema.py
tests/contrib/affiliations/test_affiliations_schema.py
tests/contrib/affiliations/test_affiliations_service.py
tests/contrib/awards/conftest.py
tests/contrib/awards/test_awards_datastreams.py
tests/contrib/names/conftest.py
tests/contrib/names/test_names_api.py
tests/contrib/names/test_names_datastreams.py
tests/contrib/names/test_names_schema.py
tests/contrib/names/test_names_service.py

- config: update awards funders mapping
- awards: add "program" field
- ci: update matrix
- global: switch names and affiliations to model PID field

Switch names and affiliations to model PID field

---

invenio_vocabularies/contrib/affiliations/facets.py

Closes https://github.com/zenodo/zenodo-rdm/issues/413
Adds `AffiliationsLabels` to get Organizations in community search

affiliations: add facet labels

---

invenio_vocabularies/services/custom_fields/vocabulary.py

* closes https://github.com/zenodo/who-rdm/issues/91

custom_fields: allow to pass schema to the VocabularyCF

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v2.1.0

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.js

**Partially Fixes Issues  [#1437](https://github.com/inveniosoftware/invenio-rdm-records/issues/1437#issue-1875533280) and [#1461 ](https://github.com/inveniosoftware/invenio-rdm-records/issues/1461#issue-1892576243)related to the Accessibility of Deposit Form** 
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …

Accessibility: fixed accessibility issue of Funding section

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v2.1.1

---

invenio_vocabularies/contrib/affiliations/facets.py
invenio_vocabularies/contrib/funders/facets.py
invenio_vocabularies/services/facets.py
tests/services/test_labels.py

To be deployed and tested in an env.

facets: implement in-memory cache

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v2.2.0

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js

Partially Closes Issue [#2455
](https://github.com/inveniosoftware/invenio-app-rdm/issues/2455)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

ui: adds focus prop to dropdown select

---

invenio_vocabularies/contrib/affiliations/facets.py
invenio_vocabularies/contrib/funders/facets.py
invenio_vocabularies/services/facets.py
tests/resources/test_tasks_resources.py
tests/services/test_labels.py

facets: cache vocabularies by id

---

invenio_vocabularies/alembic/55a700f897b6_add_names_and_afiliations_pid_column.py

* see https://github.com/inveniosoftware/invenio-pidstore/blob/master/invenio_pidstore/alembic/999c62899c20_create_pidstore_tables.py

alembic rcp: set explicit dependency on pidstore create table

---

CHANGES.rst
invenio_vocabularies/__init__.py

release: v2.2.2

---

invenio_vocabularies/contrib/awards/config.py
invenio_vocabularies/contrib/funders/config.py
tests/contrib/awards/test_awards_resource.py
tests/contrib/funders/test_funders_resource.py

* closes https://github.com/zenodo/rdm-project/issues/415
* closes https://github.com/zenodo/rdm-project/issues/425

config: suggestions for funders and awards

---

invenio_vocabularies/contrib/affiliations/config.py

closes https://github.com/zenodo/rdm-project/issues/456

config: added affiliations suggestions by id.

---

CHANGES.rst
invenio_vocabularies/__init__.py
invenio_vocabularies/datastreams/readers.py
invenio_vocabularies/datastreams/transformers.py
invenio_vocabularies/datastreams/xml.py
setup.cfg
tests/conftest.py

Bump invenio-records-resources and release v3.0.0

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js

Resolves https://github.com/inveniosoftware/invenio-app-rdm/issues/1868 by showing the country and ROR in the results. 
**Reminder**
1. You license your contribution under the same terms as the …

funding: add country and ror to funder search results

---

invenio_vocabularies/cli.py
invenio_vocabularies/factories.py
tests/test_cli.py
tests/test_factory.py

Address the `FIXME` noted in the following section: https://github.com/inveniosoftware/invenio-vocabularies/blob/a180d29f38f366b37d228314accac96fc74b6d81/invenio_vocabularies/cli.py#L27-L51
Preferably merge #297  first to pass the unrelated failing test.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …

cli : Create factory for get_config_for_ds

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js
invenio_vocabularies/contrib/funders/config.py
invenio_vocabularies/contrib/funders/datastreams.py
invenio_vocabularies/contrib/funders/jsonschemas/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/funders/mappings/os-v1/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/funders/mappings/os-v2/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/funders/mappings/v7/funders/funder-v1.0.0.json
invenio_vocabularies/contrib/funders/schema.py
tests/contrib/funders/conftest.py
tests/contrib/funders/test_funders_datastreams.py

The PR switches the funders vocabulary to use the v2 version of the ROR schema https://github.com/inveniosoftware/invenio-vocabularies/issues/316.
It adds new fields:
- aliases (aliases listed in the ROR names field)
- status (status of record in ROR)
- types (type of organization)
- country_name (full name of first country)
- location_name (name of first location)
- acronym (first acronym listed in the ROR names field)
For compatibility purposes we only include the first location and acronym. There doesn't seem to be many RORs with multiple locations or acronyms. Ideally we'd be able to include all of these, but it would require a breaking change which doesn't seem to be worth it.
It no longer assumes that the primary name is in english (which …

funders:update to ROR v2

---

invenio_vocabularies/contrib/awards/datastreams.py
tests/contrib/awards/test_awards_datastreams.py

Partially fixes #324 
The pull request fixes two problems when processing the projects from the [full OpenAIRE Graph Dataset](https://doi.org/10.5281/zenodo.3516917):
1. The identifiers do no have the `40|` prefix and cause an `IndexError: list index out of range`
2. Some projects do not have a `title` and cause a `KeyError: 'title'`
1. Go to the "OpenAIRE Graph Dataset" record: https://zenodo.org/records/10488385
2. Download `project.tar`
3. On an InvenioRDM instance, run:
```bash
invenio-cli shell
invenio vocabularies convert -v awards -o project.tar -t awards.yaml
```
* If you have added [third-party code (copy/pasted or new …

fix: awards full OpenAIRE project transformer

---

invenio_vocabularies/services/tasks.py
setup.cfg

Fixes #333 
Demo of the funders harvesting via a celery task.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the …

datastreams: funders celery task using ror-http

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingModal.js
invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/NoAwardResults.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2602

funding: update award label

---

invenio_vocabularies/cli.py
invenio_vocabularies/config.py
invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/contrib/names/s3client.py
invenio_vocabularies/datastreams/datastreams.py
invenio_vocabularies/datastreams/readers.py
invenio_vocabularies/datastreams/tasks.py
invenio_vocabularies/datastreams/writers.py
setup.cfg
tests/datastreams/conftest.py
tests/datastreams/test_datastreams.py
tests/datastreams/test_datastreams_tasks.py
tests/resources/test_tasks_resources.py
tests/test_cli.py
tests/test_factory.py

* closes https://github.com/inveniosoftware/invenio-vocabularies/issues/353

Add orcid data sync

---

invenio_vocabularies/contrib/affiliations/affiliations.py
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/contrib/subjects/subjects.py

* closes https://github.com/zenodo/rdm-project/issues/598

http headers: use and adjust vnd.inveniordm.v1+json http accept header

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/package.json
invenio_vocabularies/webpack.py

* closes https://github.com/zenodo/rdm-project/issues/657

package: bump react-invenio-forms

---

CHANGES.rst
invenio_vocabularies/__init__.py
invenio_vocabularies/contrib/awards/schema.py
invenio_vocabularies/contrib/awards/serializer.py
invenio_vocabularies/contrib/names/names.py
invenio_vocabularies/contrib/subjects/schema.py
tests/contrib/names/test_names_resource.py
tests/datastreams/test_transformers.py

📦 release: v6.0.0

---

invenio_vocabularies/contrib/common/ror/datastreams.py
invenio_vocabularies/jobs.py
setup.cfg

jobs: add job to process funders

---

invenio_vocabularies/config.py

Fixes #427 
* The previous default URL was the one corresponding to EuroSciVoc v1.4
* The new URL is version-less and points to the latest version of EuroSciVoc (current v1.5)
* See linked issue for more details
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository- …

subjects: euroscivoc: change default to latest version-less URL

---

CHANGES.rst
invenio_vocabularies/__init__.py
invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/datastreams/datastreams.py
invenio_vocabularies/datastreams/writers.py
invenio_vocabularies/services/tasks.py
tests/conftest.py

* closes https://github.com/inveniosoftware/invenio-jobs/issues/67

logging: add basic logging for ORCID

---

invenio_vocabularies/contrib/common/ror/datastreams.py
tests/contrib/common/ror/test_ror_datastreams.py

Adding basic logging to ROR HTTP reader.
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …

logging: add basic logging for ROR HTTP reader

---

invenio_vocabularies/config.py

idutils may be deprecating implicit imports https://github.com/inveniosoftware/idutils/blob/f02d935e6af2d1e5019f62bed72e7ebeec62f9aa/idutils/__init__.py#L23, so we shouldn't use them here.
**Reminder**
1. You license your contribution …

config: update idutils imports

---

invenio_vocabularies/contrib/names/datastreams.py

* Fixes zenodo/zenodo-rdm#1176
* For Zenodo, we decided that we should not only **import** (aka insert-only) ORCID entries, but that we should also **update**
* This pull request proposes to create a new task so that users of jobs have a choice between both options
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-cont …

jobs: ORCID job update instead of import (insert-only)

---

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.js

Closes issue https://github.com/inveniosoftware/invenio-rdm-records/issues/2051
**Frontend**
**Reminder**
2. You agree that you have the right to …

funding: added fieldpath prop for feedback label

---

invenio_vocabularies/services/tasks.py

* NEEDS  https://github.com/inveniosoftware/invenio-jobs/pull/84

tasks: fix error name

---

invenio_vocabularies/contrib/names/datastreams.py
invenio_vocabularies/datastreams/datastreams.py
invenio_vocabularies/datastreams/tasks.py
invenio_vocabularies/datastreams/writers.py
invenio_vocabularies/services/tasks.py
tests/datastreams/test_writers.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/430

datastreams: improve async writer
