inveniosoftware/invenio-vocabularies

invenio_vocabularies/cli.py, invenio_vocabularies/resources/resource.py, invenio_vocabularies/services/permissions.py, invenio_vocabularies/version.py, setup.py, tests/conftest.py, tests/services/conftest.py, tests/services/test_permissions.py
closes #22 
requires the `SystemProcess` generator defined in https://github.com/inveniosoftware/invenio-records-permissions/pull/62
=> 22 read only vocabularies

setup.py
closes inveniosoftware/invenio-rdm-records#441
add a new service method for reindexing vocabularies
EDIT: this one basically reverted to a bump of invenio-db, because `rebuild_index` has been moved to `invenio-records-resources` (inveniosoftware/invenio-records-resources/pull/211)
=> bump invenio-db (formerly: add service.rebuild_index)

invenio_vocabularies/services/facets.py, invenio_vocabularies/services/service.py
requires https://github.com/inveniosoftware/invenio-records-resources/pull/250
closes #38 
- Note there is a parameter order change in the service methods to make the vocabulary type mandatory
- No tests are added since the method was already tested by the `test_facets.py` (not a valid excuse, but is good for now)
=> services: add support for filtered read_all

invenio_vocabularies/services/facets/__init__.py, invenio_vocabularies/services/facets/facets.py, invenio_vocabularies/services/facets/labels.py, tests/services/conftest.py, tests/services/test_facets.py, tests/services/test_labels.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/628
Example output for resource_types:
```
{
"aggregations": {
"resource_type": {
"buckets": [
{
"key": "image",
"doc_count": 10,
"label": "Image",
"is_selected": false,
"inner": {
"buckets": [
{
"key": "image-diagram",
"doc_count": 4,
"label": "Diagram",
"is_selected": false
},
{
"key": "image-other",
"doc_count": 6,
"label": "Other",
"is_selected": false
}
]
},
...
```
=> facets: add nested vocabulary facet and label

tests/conftest.py, tests/services/test_service.py
=> test: read_all tested with and without cache

invenio_vocabularies/translations/en/LC_MESSAGES/messages.po
* At least one message catalog is required for compile_catalog to work
otherwise the PyPI publishing will fail.
=> i18n: fix missing message catalog

invenio_vocabularies/contrib/affiliations/schema.py, invenio_vocabularies/contrib/awards/__init__.py, invenio_vocabularies/contrib/awards/schema.py, invenio_vocabularies/contrib/funders/__init__.py, invenio_vocabularies/contrib/funders/schema.py, invenio_vocabularies/version.py, tests/contrib/affiliations/test_affiliations_schema.py, tests/contrib/awards/test_awards_schema.py, tests/contrib/funders/test_funders_schema.py
* Moving schemas from Invenio-RDM-Records to Invenio-Vocabularies so
that a dependency among Invenio-RDM-Records and Invenio-Communities
can be broken.
=> contrib: relation schemas

invenio_vocabularies/contrib/names/datastreams.py, invenio_vocabularies/datastreams/readers.py, tests/contrib/names/test_names_datastreams.py
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/126
Example of programmatic usage (which is the flow of datastream aprox):
```
>>> from invenio_vocabularies.contrib.names.datastreams import OrcidHTTPReader, OrcidXMLTransformer
>>> reader = OrcidHTTPReader(orcid_id="0000-0001-6759-6273", test_mode=False)
>>> OrcidXMLTransformer().apply(reader.read())
{'given_name': 'Pablo', 'family_name': 'Panero', 'identifiers': [{'scheme': 'orcid', 'identifier': 'https://orcid.org/0000-0001-6759-6273'}], 'affiliations': []}
```
=> contrib: add orcid http reader for names

invenio_vocabularies/datastreams/transformers.py, tests/datastreams/test_transformers.py
closes https://github.com/inveniosoftware/invenio-vocabularies/issues/131
The `XMLTransformer` was more of a mixin than an actual base class since it did not implement correctly the API. Now it has a default apply, where all records would be returned fully as long as the base element is called `record`.
=> datastreams: implement default apply for xml transformer

invenio_vocabularies/cli.py, invenio_vocabularies/contrib/names/datastreams.py, invenio_vocabularies/datastreams/datastreams.py, invenio_vocabularies/datastreams/readers.py, invenio_vocabularies/datastreams/transformers.py, invenio_vocabularies/datastreams/writers.py, tests/contrib/names/test_names_datastreams.py, tests/datastreams/conftest.py, tests/datastreams/test_writers.py, tests/test_cli.py
closes #86 
Implements changes on the `ServiceWrite` to allow updating a record if it exists, by doing this the rest of the pipeline (readers, transformers) stay the same.
=> cli: implement update command and adapt service writer

invenio_vocabularies/resources/resource.py, invenio_vocabularies/services/permissions.py, invenio_vocabularies/services/schema.py, invenio_vocabularies/services/service.py, invenio_vocabularies/services/tasks.py, tests/datastreams/test_datastreams.py, tests/resources/conftest.py, tests/resources/test_tasks_resources.py, tests/services/test_schema.py
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/125
**I am not convinced of the implementation**, it looks a bit ad-hoc (no uow, adding `task_schema` to the config, and so on). IMO, it should be a separate resource (like PIDs in `invenio-rdm-records`) but this serves as PoC.
@slint might be missing a test at service level... but is indirectly tested by the resource since the tasks are run eagerly in tests.
=> Tasks REST API

invenio_vocabularies/contrib/names/datastreams.py, tests/contrib/names/test_names_datastreams.py, tests/test_cli.py
closes #137 
I've also run the test suit of `rdm-records` and `app-rdm` and no changes are needed in these repos. Tested the config in `app-rdm` is loaded correctly:
```
In [3]: current_app.config["VOCABULARIES_DATASTREAM_TRANSFORMERS"]
Out[3]:
{'xml': invenio_vocabularies.datastreams.transformers.XMLTransformer,
'orcid': invenio_vocabularies.contrib.names.datastreams.OrcidTransformer}
```
Very nice catch with the `**`, kudos @slint
=> contrib(names): split xml and orcid transformers

invenio_vocabularies/config.py, setup.py
Tested on a demo instance, `0000 0001 1456 7559` was detected as *isni* and publishing succeeded.
EDIT: Tests are breaking due to the upgrade of `invenio-jsonschemas` importlib vs pkg_resources. The `extra_entry_points` fixture does not seem to work as expected
=> config: add isni to names schemas

invenio_vocabularies/cli.py, invenio_vocabularies/config.py, invenio_vocabularies/contrib/funders/config.py, invenio_vocabularies/contrib/funders/datastreams.py, invenio_vocabularies/contrib/names/datastreams.py, invenio_vocabularies/datastreams/datastreams.py, invenio_vocabularies/datastreams/factories.py, invenio_vocabularies/datastreams/readers.py, invenio_vocabularies/fixtures.py, invenio_vocabularies/services/schema.py, invenio_vocabularies/services/tasks.py, tests/contrib/funders/test_funders_datastreams.py, tests/contrib/funders/test_funders_resource.py, tests/contrib/names/test_names_datastreams.py, tests/datastreams/conftest.py, tests/datastreams/test_datastreams.py, tests/datastreams/test_readers.py, tests/datastreams/vocabularies.yaml, tests/resources/test_tasks_resources.py, tests/services/test_schema.py
requires https://github.com/inveniosoftware/invenio-vocabularies/pull/155
closes https://github.com/inveniosoftware/invenio-vocabularies/issues/148
Example imported from the dump:
```json
{
"pid": "04j757h98",
"name": "Victoria University",
"created": "2022-03-21T16:11:03.049346+00:00",
"id": "a73cad48-a30b-4cc7-b4aa-366a201a2029",
"country": "AU",
"title": {},
"links": {
"self": "https://127.0.0.1:5000/api/funders/04j757h98"
},
"updated": "2022-03-21T16:11:03.059741+00:00",
"identifiers": [
{
"scheme": "isni",
"identifier": "0000 0001 0396 9544"
},
{
"scheme": "doi",
"identifier": "10.13039/501100001784"
},
{
"scheme": "grid",
"identifier": "grid.1019.9"
}
],
"revision_id": 2
}
```
Rebasing multiple PRs has created a bit of conflicts, should be solved once the required PRs are merged. …
=> datastreams: funders readers and transformers

invenio_vocabularies/contrib/awards/config.py, invenio_vocabularies/contrib/funders/facets.py, invenio_vocabularies/contrib/funders/services.py, invenio_vocabularies/services/facets.py, tests/contrib/awards/conftest.py, tests/contrib/awards/test_awards_resource.py
- requires #163 
- closes https://github.com/inveniosoftware/invenio-vocabularies/issues/168 
- Enable customization of service used to get the vocabularies when calculating the facet labels.
- Enable customization of the label string (i.e. not just `title`).
- Implements a `FundersLabels`, with the corresponding changes in `service.read_many`.
=> Awards facets

invenio_vocabularies/cli.py, invenio_vocabularies/contrib/affiliations/schema.py, invenio_vocabularies/contrib/funders/schema.py, invenio_vocabularies/contrib/subjects/schema.py
Refs https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
=> i18n: Fixes strings mainly marked for translation.

.github/workflows/tests-feature.yaml, .github/workflows/tests.yml, invenio_vocabularies/contrib/affiliations/mappings/os-v1/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/affiliations/mappings/os-v2/__init__.py, invenio_vocabularies/contrib/affiliations/mappings/os-v2/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/affiliations/mappings/v7/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/os-v1/awards/award-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/os-v2/__init__.py, invenio_vocabularies/contrib/awards/mappings/os-v2/awards/award-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/v7/awards/award-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/os-v1/funders/funder-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/os-v2/__init__.py, invenio_vocabularies/contrib/funders/mappings/os-v2/funders/funder-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/v7/funders/funder-v1.0.0.json, invenio_vocabularies/contrib/names/mappings/os-v2/__init__.py, invenio_vocabularies/contrib/names/mappings/os-v2/names/name-v1.0.0.json, invenio_vocabularies/contrib/subjects/mappings/os-v2/__init__.py, invenio_vocabularies/contrib/subjects/mappings/os-v2/subjects/subject-v1.0.0.json, invenio_vocabularies/records/mappings/os-v2/__init__.py, invenio_vocabularies/records/mappings/os-v2/vocabularies/vocabulary-v1.0.0.json, setup.cfg, tests/contrib/affiliations/test_affiliations_api.py, tests/contrib/awards/test_awards_api.py, tests/contrib/funders/test_funders_api.py, tests/contrib/names/test_names_api.py, tests/contrib/subjects/test_subjects_api.py, tests/records/conftest.py, tests/records/test_relationship.py
There's still an issue going on with the suggestions for contrib vocabularies...
The following errors only happen with OSv2, but neither OSv1 nor ES7:
```
> /home/mmoser/rdm/opensearch2/invenio-vocabularies/tests/contrib/affiliations/test_affiliations_resource.py(130)test_affiliations_suggest_sort()
128     # Should show 2 results, but id=cern as first due to acronym/name
129     res = client.get(f"{prefix}?suggest=CERN", headers=h)
--> 130     assert res.status_code == 200
131     assert res.json["hits"]["total"] == 2
132     assert res.json["hits"]["hits"][0]["id"] == "cern"
ipdb> res.text
'{"status": 400, "message": "Invalid query string syntax."}'
```
Without the `?suggest=CERN` part, it works:
```
ipdb> client.get(f"{prefix}", headers=h).text
'{"hits": {"hits": [{"acronym": "CERN", …
```
=> OpenSearch 2.x

invenio_vocabularies/services/service.py
Set more specific `indexer_queue_name` for the service configs to avoid clashes with other unrelated services' indexing task queue names.
This is related to https://github.com/inveniosoftware/invenio-records-resources/pull/419.
=> Set `indexer_queue_name` in the service configs

invenio_vocabularies/services/facets.py
- requires https://github.com/inveniosoftware/invenio-records-resources/pull/435
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1952
In invenio-vocabularies we have `read`, `read_all` and `read_many`. When searching for generic vocabularies, we give two parameters vocabulary `type` and `ids` (e.g. _resourcetype_ and _publication_). In the case that publication does not exist the result would be:
- `read` --> `NoResultFound` (404) 
- `read_many` and `read_all` --> empty search result (i.e. `hits: []`)
However, all three methods assume that the vocabulary type (e.g. _resourcetype_) exists in db (we are querying `.one()` with no try/except). Then, it make the search page with a 404 because a `NoResultFound` is risen. It leads me to:
- `read` --> `NoResultFound` (404) . …
=> facets: handle non-existent vocabulary type

invenio_vocabularies/contrib/funders/datastreams.py, tests/contrib/funders/test_funders_datastreams.py
Adding ROR as a funder identifier when ROR is loaded through the datastream. This is the case in the demo data (https://inveniordm.web.cern.ch/api/funders), but not when funders are loaded through the datastream. When the ROR is not present in the identifiered, the DataCite serializer doesn't behave as expected https://github.com/inveniosoftware/invenio-rdm-records/issues/1038.  …
=> funders: add ROR to identifiers for all funders in datastream

CHANGES.rst, invenio_vocabularies/__init__.py, invenio_vocabularies/config.py, invenio_vocabularies/contrib/affiliations/config.py, invenio_vocabularies/contrib/affiliations/schema.py, invenio_vocabularies/contrib/awards/config.py, invenio_vocabularies/contrib/awards/datastreams.py, invenio_vocabularies/contrib/awards/schema.py, invenio_vocabularies/contrib/funders/config.py, invenio_vocabularies/contrib/funders/datastreams.py, invenio_vocabularies/contrib/funders/schema.py, invenio_vocabularies/contrib/names/config.py, invenio_vocabularies/contrib/names/schema.py, invenio_vocabularies/contrib/subjects/config.py, invenio_vocabularies/contrib/subjects/schema.py, invenio_vocabularies/resources/serializer.py, invenio_vocabularies/services/components.py, invenio_vocabularies/services/schema.py, invenio_vocabularies/services/service.py, run-tests.sh, setup.cfg, tests/contrib/awards/conftest.py, tests/resources/test_resources_l10n.py
- migrate: flask_babelex replaced by invenio_i18n
- tests: fix extract_messages --dry-run
- fix: different client.get calls uses one namespace
- NOTE: invenio-i18n, invenio-accounts, invenio-theme has to be released before
=> migrate to flask babel

.github/workflows/tests.yml, invenio_vocabularies/alembic/4a9a4fd235f8_create_vocabulary_schemes.py, invenio_vocabularies/alembic/4f365fced43f_create_vocabularies_tables.py, invenio_vocabularies/alembic/676dd587542d_create_funders_vocabulary_table.py, invenio_vocabularies/alembic/e1146238edd3_create_awards_table.py, invenio_vocabularies/contrib/awards/awards.py, invenio_vocabularies/contrib/funders/funders.py, invenio_vocabularies/records/models.py, run-tests.sh, tests/test_alembic.py
This PR includes some mysql tests. This is related to https://github.com/inveniosoftware/invenio-app-rdm/issues/2232
The main issue is that `user_resources` is tested both in mysql and postgress. The mysql tests failed, since vocabularies did not define the length of the fields. 
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> Including mysql tests

CHANGES.rst, invenio_vocabularies/__init__.py, invenio_vocabularies/contrib/names/schema.py
- contrib: fix `name` dumping for Names vocabulary
- release: v2.2.3
=> Names serialization fix and release v2.2.3

CHANGES.rst, invenio_vocabularies/__init__.py, invenio_vocabularies/contrib/affiliations/config.py, tests/contrib/affiliations/test_affiliations_resource.py
* closes https://github.com/zenodo/rdm-project/issues/394
what will not work is if you make a typo, suggestions will not kick in because they are defined on title
=> Fix search clauses

invenio_vocabularies/contrib/names/schema.py, tests/contrib/names/test_names_schema.py
* closes https://github.com/zenodo/rdm-project/issues/530
=> schema: add validation for affiliations

invenio_vocabularies/contrib/affiliations/mappings/os-v1/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/affiliations/mappings/os-v2/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/affiliations/mappings/v7/affiliations/affiliation-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/os-v1/awards/award-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/os-v2/awards/award-v1.0.0.json, invenio_vocabularies/contrib/awards/mappings/v7/awards/award-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/os-v1/funders/funder-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/os-v2/funders/funder-v1.0.0.json, invenio_vocabularies/contrib/funders/mappings/v7/funders/funder-v1.0.0.json, invenio_vocabularies/records/mappings/os-v1/vocabularies/vocabulary-v1.0.0.json, invenio_vocabularies/records/mappings/os-v2/vocabularies/vocabulary-v1.0.0.json, invenio_vocabularies/records/mappings/v7/vocabularies/vocabulary-v1.0.0.json, invenio_vocabularies/services/custom_fields/vocabulary.py, tests/custom_fields/test_custom_fields.py, tests/mock_module/mappings/v6/records/record-v1.0.0.json, tests/mock_module/mappings/v7/records/record-v1.0.0.json
- The mapping is stored as a string/enum in ES/OS. Using the same type makes sure the mapping comparison is correct when performing a mapping update.
=> mappings: change "dynamic" values to string

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js, invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingField.js
Added additional Overridable tags for a more finegrained control over React components.
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
=> Add overridable tags

invenio_vocabularies/contrib/awards/datastreams.py, invenio_vocabularies/contrib/funders/datastreams.py, invenio_vocabularies/contrib/names/datastreams.py, tests/datastreams/test_datastreams.py
Partially fixes #305 
:books: Quoting the [ROR data dump documentation](https://ror.readme.io/docs/data-dump):
> Beginning with release v1.45 on 11 April 2024, data releases contain JSON and CSV files formatted according to both schema v1 and schema v2. Version 2 files have `_schema_v2` appended to the end of the filename, e.g., `v1.45-2024-04-11-ror-data_schema_v2.json`. In order to maintain compatibility with previous release, version 1 files have no version information in the filename, e.g., `v1.45-2024-04-11-ror-data.json`.
:bomb: This breaks the funders convert script, which goes through both v1 and v2 files:
```bash
$ invenio vocabularies convert -v funders -o v1.46-2024-05-02-ror-data.zip -t affiliations_ror.yaml
[...]
RORTransformer: Name …
```
=> Funders: fix: exclude ROR schema v2 json

invenio_vocabularies/contrib/common/__init__.py, invenio_vocabularies/contrib/common/ror/__init__.py, invenio_vocabularies/contrib/common/ror/datastreams.py, invenio_vocabularies/datastreams/readers.py, tests/contrib/common/ror/test_ror_datastreams.py, tests/datastreams/test_readers.py
* Fixes #311
> **Quoted description**:
> * Automatically download the latest ROR data dump file
> * Stream it to the next reader/transformer without relying on the file system.
* How to review this Pull Request:
* This Pull Request is separated in **3 logical commits**, I recommended to **review them one by one**.
* The **changes can be tested** in an InvenioRDM instance by doing:
```bash
$ invenio-cli shell
$ invenio vocabularies convert -v funders -o dummy -t funders.yaml
Vocabulary funders converted. Total items 109355. 
109355 items succeeded
0 contained errors
0 were filtered.
```
* If you have added [third-party code (copy/pasted or new …
=> datastreams: add ROR HTTP reader and use it for funders

invenio_vocabularies/contrib/awards/datastreams.py, invenio_vocabularies/datastreams/readers.py, tests/contrib/awards/test_awards_datastreams.py, tests/contrib/common/ror/test_ror_datastreams.py, tests/datastreams/test_readers.py
* Fixes #324 
> **Quoted description**:
> * Automatically download the latest OpenAIRE Graph dataset.
> * Allow to choose between the full dataset or the differential one.
> * Stream it to the next reader/transformer without relying on the file system.
* How to review this Pull Request:
* This Pull Request is separated in **4 logical commits**, I recommended to **review them one by one**.
* The **changes can be tested** in an InvenioRDM instance by
* Integrating the changes from
* inveniosoftware/invenio-app-rdm#2676
* #328
* doing:
```bash
$ invenio-cli shell
$ invenio vocabularies convert -v awards -o diff -t awards.yaml
$ invenio vocabularies convert -v awards -o full -t awards.yaml
```
Ticks in all boxes and 🟢 on all GitHub actions status …
=> awards: datastreams: add OpenAIRE Project HTTP Reader

CHANGES.rst, invenio_vocabularies/__init__.py, setup.cfg
- Major release of `invenio-vocabularies` due to breaking changes in CLI and added mappings
- Major bump of `invenio-records-resources`
=> release: v4.0.0

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/CustomAwardForm.js, invenio_vocabularies/contrib/funders/serializer.py
* Fixes #342
* The 1st commit includes the country_name in the API response for funders which have a country_name (recently  updated ones)
* The pull request inveniosoftware/invenio-app-rdm#2704 modifies `deserializeFunder` to pass include country_name in the deserialized form of funder items.
* The 2nd commit simplifies the logic of `deserializeFunderToDropdown` by using optional chaining
* The 3rd commit modifies `deserializeFunderToDropdown` to shows the country code for existing funders which don't have yet a country_name
* Note that the modified `deserializeFunder` function is used lower down in the `render` function of `CustomAwardForm`.
Places which might need to be modified to also include country_name:
Ticks in all boxes and 🟢 on all …
=> Fix funders show country

invenio_vocabularies/contrib/names/config.py, invenio_vocabularies/contrib/names/mappings/os-v1/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/mappings/os-v2/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/names.py, tests/contrib/names/test_names_datastreams.py, tests/contrib/names/test_names_resource.py
Fixes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2756
The names in the database and index are inverted, therefore the suggest API first tries to search on the last name and prioritizes that due to how edge ngram works for the suggest API.
This solution add suggest API for given name for better results.
tests fail due to https://github.com/inveniosoftware/invenio-vocabularies/pull/372, to be rebased and merged after #372
=> contrib: names: update field boosts and mapping

invenio_vocabularies/contrib/common/ror/datastreams.py, invenio_vocabularies/contrib/subjects/schema.py, tests/contrib/common/ror/test_ror_datastreams.py, tests/contrib/subjects/test_subjects_datastreams.py
Requires https://github.com/inveniosoftware/invenio-rdm-records/pull/1798 to be merged and deployed on Zenodo (so that the JSON-LD export format includes the `dateCreated` field)
=> ror: fix dump modified date comparison

invenio_vocabularies/config.py, invenio_vocabularies/contrib/subjects/datastreams.py, invenio_vocabularies/contrib/subjects/euroscivoc/__init__.py, invenio_vocabularies/contrib/subjects/euroscivoc/datastreams.py, invenio_vocabularies/contrib/subjects/jsonschemas/subjects/subject-v1.0.0.json, invenio_vocabularies/contrib/subjects/mappings/os-v1/subjects/subject-v1.0.0.json, invenio_vocabularies/contrib/subjects/mappings/os-v2/subjects/subject-v1.0.0.json, invenio_vocabularies/contrib/subjects/mappings/v7/subjects/subject-v1.0.0.json, invenio_vocabularies/contrib/subjects/mesh/__init__.py, invenio_vocabularies/contrib/subjects/schema.py, setup.cfg, tests/contrib/subjects/euroscivoc/test_subjects_euroscivoc_datastream.py
Closes Issue https://github.com/inveniosoftware/invenio-vocabularies/issues/381
Closes https://github.com/zenodo/zenodo-rdm/issues/986
**Hierarchy:**
_agricultural sciences > agricultural biotechnology > agricultural genetics > livestock cloning_
_27 > 79 > 483 > 1273_
**Subject:** Livestock cloning
e.g
```json
{
"id": "euroscivoc:1273",
"pid": {
"pk": 13377,
"status": "R",
"obj_type": "rec",
"pid_type": "sub"
},
"props": {
"parents": "euroscivoc:27,euroscivoc:79,euroscivoc:483"
},
"title": {
"de": "Klonen von Tieren",
"en": "livestock cloning",
"es": "clonación de ganado",
"fr": "clonage du bétail",
"it": "clonazione animale",
"pl": "klonowanie zwierząt gospodarskich"
},
"scheme": "EuroSciVoc",
"$schema": "local://subjects/subject-v1.0.0.json",
"subject": "Livestock cloning", …
```
=> subjects: added euroscivoc datastream

invenio_vocabularies/contrib/names/names.py, invenio_vocabularies/contrib/names/permissions.py, tests/contrib/names/test_names_resource.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/191
=> resource: add permission check to names search

invenio_vocabularies/contrib/common/ror/datastreams.py, invenio_vocabularies/jobs.py, setup.cfg
* closes https://github.com/inveniosoftware/invenio-jobs/issues/49
=> jobs: register RoR affiliation job

invenio_vocabularies/contrib/awards/datastreams.py, tests/contrib/awards/test_awards_datastreams.py
Fixes #417
This pull request contains the logic for extracting the program from CORDIS.
The logic can be tested with the following commands:
```bash
invenio vocabularies convert -v awards:cordis -o "HE" -t he.yaml
invenio vocabularies convert -v awards:cordis -o "H2020" -t h2020.yaml
invenio vocabularies convert -v awards:cordis -o "FP7" -t fp7.yaml
```
Here are how many projects for each program is found for each of the 3 input files:
```
13674 entries in the HE file
57 program: EURATOM
3582 program: ERC
4585 program: MSCA
5450 program: Other HORIZON programmes
35386 entries in the H2020 file
99 program: EURATOM
7850 program: ERC
11807 program: MSCA
15630 program: Other H2020 programmes
19814 entries in the FP7 file
125 program: EURATOM
3151 …
```
=> awards: get program from CORDIS

CHANGES.rst, invenio_vocabularies/__init__.py, invenio_vocabularies/jobs.py
This fixes the error `TypeError: can not serialize 'datetime.datetime' object` which happens when scheduling a job with the stack trace:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 41, in _reraise_errors
yield
File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 220, in dumps
payload = encoder(data)
File "/usr/local/lib/python3.9/site-packages/kombu/serialization.py", line 368, in pack
return packb(s, use_bin_type=True)
File "/usr/local/lib64/python3.9/site-packages/msgpack/__init__.py", line 36, in packb
```
=> jobs: pass since as string to task

invenio_vocabularies/contrib/awards/datastreams.py, tests/contrib/awards/test_awards_datastreams.py
Partially fixes #417
* In #402 we changed from storing only a program like `HE` to storing the full string `EC::HE::HORIZON-TMA-MSCA-DN-ID`, because we thought was we would be able to easily identify sub-programmes like MSCA, ERC and EURATOM like this.
* In the end, we are now getting the more detailed sub-programmes from CORDIS (see #412).
* We are proposing to rollback this change so that if the project does not exist yet in CORDIS (this is for instance the case of https://cordis.europa.eu/project/id/101196872), then we can still fall back on `HE` and at least know that this is not `H2020` and `FP7` (although we won't be able to know if it's MSCA, ERC or EURATOM). …
=> awards: rollback to use the 2nd part of funding stream as program

invenio_vocabularies/contrib/funders/mappings/os-v1/funders/funder-v2.0.0.json, invenio_vocabularies/contrib/funders/mappings/os-v2/funders/funder-v2.0.0.json
Close #408 
The normalizer that was introduced in the funders index with v5.1.0 generates two tokens when used on documents that contain diacritics in the acronym. This behaviour occurs when in the filter definition `"preserve_original": true` is used. This is ok for analyzers, so this PR just renames the filters and takes care the analyzers use the new ones and the normailzer uses the original ones.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members). …
=> Rename patched filters so the normalizer uses the default ones

invenio_vocabularies/contrib/affiliations/affiliations.py, invenio_vocabularies/contrib/awards/awards.py, invenio_vocabularies/contrib/funders/funders.py, invenio_vocabularies/contrib/names/jsonschemas/names/name-v1.0.0.json, invenio_vocabularies/contrib/names/mappings/os-v1/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/mappings/os-v2/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/permissions.py, invenio_vocabularies/contrib/names/schema.py, invenio_vocabularies/contrib/names/services.py, invenio_vocabularies/services/generators.py, invenio_vocabularies/services/permissions.py, tests/conftest.py, tests/contrib/names/conftest.py, tests/contrib/names/test_name_permissions.py, tests/contrib/names/test_names_api.py, tests/services/test_permissions.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/193
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/194
=> Add non-searchable tags

invenio_vocabularies/assets/semantic-ui/js/invenio_vocabularies/src/contrib/forms/Funding/FundingModal.js, invenio_vocabularies/contrib/awards/schema.py
Hi, in order to enable institutions to use a less strict validation for funding entries that still adheres to Datacite this PR adds a global conf variable that when set allows an alternative validation of a funding entry. 
Right now Invenio wants if either an award number or title is entered the other:
This is not required by DataCite: https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/fundingreference/
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/arch …
=> awards/schema.py: read app config for alternate funding validation

invenio_vocabularies/config.py, invenio_vocabularies/contrib/subjects/config.py, invenio_vocabularies/contrib/subjects/datastreams.py, invenio_vocabularies/contrib/subjects/euroscivoc/datastreams.py, invenio_vocabularies/contrib/subjects/gemet/__init__.py, invenio_vocabularies/contrib/subjects/gemet/datastreams.py, invenio_vocabularies/contrib/subjects/jsonschemas/subjects/subject-v1.0.0.json, invenio_vocabularies/contrib/subjects/schema.py, invenio_vocabularies/datastreams/readers.py, invenio_vocabularies/datastreams/transformers.py, tests/contrib/subjects/euroscivoc/test_subjects_euroscivoc_datastream.py, tests/contrib/subjects/gemet/test_subjects_gemet_datastream.py
Closes Issue https://github.com/inveniosoftware/invenio-vocabularies/issues/434
Adding a new hierarchal vocabulary [GEMET](https://www.eionet.europa.eu/gemet/en/about/)
**/api/subjects**
```json=
{
"id": "gemet:concept/11",
"created": "2024-11-19T15:41:32.341318+00:00",
"updated": "2024-11-19T15:41:32.354614+00:00",
"links": {
"self": "https://127.0.0.1:5000/api/subjects/gemet%3Aconcept%2F11"
},
"revision_id": 1,
"title": {
"ar": "عامل لاحيوي",
"az": "Abiotik amil",
"bg": "Абиотичен фактор",
"ca": "Factor abiòtic",
"cs": "Činitel abiotický",
"da": "Abiotiske faktorer",
"de": "Abiotischer faktor",
"el": "Αβιοτικός παράγοντας",
"en": "Abiotic factor",
"es": "Factor abiótico",
"et": "Abiootiline tegur",
"eu": "Faktore abiotiko",
"fi": "Abioottinen …
```
=> Gemet vocab

.github/workflows/tests.yml, invenio_vocabularies/config.py, invenio_vocabularies/contrib/affiliations/config.py, invenio_vocabularies/contrib/affiliations/datastreams.py, invenio_vocabularies/contrib/subjects/euroscivoc/datastreams.py, invenio_vocabularies/contrib/subjects/gemet/datastreams.py, invenio_vocabularies/datastreams/readers.py, invenio_vocabularies/datastreams/transformers.py, invenio_vocabularies/factories.py, setup.cfg, tests/contrib/affiliations/test_affiliations_datastreams.py, tests/contrib/subjects/euroscivoc/test_subjects_euroscivoc_datastream.py, tests/contrib/subjects/gemet/test_subjects_gemet_datastream.py
Fixes #433 
The pull requests provides a new datastream to import affiliations from the [European Directory of Marine Organisations (EDMO)](https://edmo.seadatanet.org/).
There is no official mapping between EDMO and ROR, so for now we are importing them separately with a different main ID scheme.
There is no downloadable RDF file containing all the data, so we need to call a SPARQL endpoint in order to import the data.
The data can be imported with the following command:
```bash
$ invenio vocabularies import --vocabulary affiliations:edmo --origin https://edmo.seadatanet.org/sparql/sparql
EDMOOrganizationTransformer: ["No alpha_2 country found for: {'org': {'type': 'uri', 'value': 'https://edmo.seadatanet.org/report/1051'}, 'name': {'type': …
```
=> datastreams: affiliations: add EDMO organizations

invenio_vocabularies/contrib/affiliations/config.py, invenio_vocabularies/contrib/funders/config.py, invenio_vocabularies/contrib/names/config.py, invenio_vocabularies/contrib/names/mappings/os-v1/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/mappings/os-v2/names/name-v2.0.0.json, invenio_vocabularies/contrib/names/names.py, invenio_vocabularies/contrib/names/schema.py, invenio_vocabularies/services/config.py, tests/contrib/names/test_names_resource.py
- Closes https://github.com/inveniosoftware/invenio-vocabularies/issues/438
- Depends on https://github.com/inveniosoftware/invenio-records-resources/pull/602
- **names: add affiliation acronym in mappings and schema**
* Dereferences the affiliation `acronym` when indexing names and serving
REST API results. This is useful for disambiguating authors in search.
- **contrib: improve search accuracy for names, funders, affiliations**
=> Improve search accuracy for names, affiliations, funders

invenio_vocabularies/config.py, invenio_vocabularies/contrib/names/datastreams.py, tests/contrib/names/test_names_datastreams.py, tests/datastreams/test_transformers.py
- Closes #442.
- **names: extract affiliation identifiers from employments**
- **names: support mapping ORCiD org IDs to linked affiliation IDs**
=> names: link affiliations IDs from ORCiD parsing

invenio_vocabularies/contrib/subjects/config.py, invenio_vocabularies/services/querystr.py, tests/contrib/subjects/test_subjects_resource.py
* Fixes #447 (see details in linked issue)
* The feature allowing to search by prefix (e.g. `EuroSciVoc:dementia`) used to have a corresponding UI automatically adding the prefixed filter.
Now that this is not in the UI anymore, since this search behavior is not documented, and since the search results of `FilteredSuggestQueryParser` are not good, we are proposing to:
* Deprecate `FilteredSuggestQueryParser`
* Use the recently introduced `CompositeSuggestQueryParser`, which narrows down results as more search terms are added
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-p …
=> subjects: improve search with CompositeSuggestQueryParser

invenio_vocabularies/config.py, invenio_vocabularies/contrib/subjects/bodc/__init__.py, invenio_vocabularies/contrib/subjects/bodc/datastreams.py, invenio_vocabularies/contrib/subjects/config.py, invenio_vocabularies/contrib/subjects/datastreams.py, invenio_vocabularies/contrib/subjects/euroscivoc/datastreams.py, invenio_vocabularies/contrib/subjects/gemet/datastreams.py, invenio_vocabularies/datastreams/transformers.py, invenio_vocabularies/factories.py, tests/contrib/subjects/bodc/test_subjects_bodc_datastream.py, tests/contrib/subjects/gemet/test_subjects_gemet_datastream.py
Closes https://github.com/inveniosoftware/invenio-vocabularies/issues/444
**record**
```json
"subjects": [
{
"id": "SDN:P01::SAGEMSFM",
"subject": "AMSSedAge",
"scheme": "BODC-PUV",
"@v": "209a4630-6dad-4609-9d91-d832ab6f15cc::1"
},
{
"id": "SDN:P01::ZAGESCBX",
"subject": "Shell14CAge",
"scheme": "BODC-PUV",
"@v": "74da087d-601c-4aaa-b3d6-67f91e04c541::1"
}
],
```
**db**
```json
{
"id": "SDN:P01::SAGEMSGB",
"pid": {
"pk": 172411,
"status": "R",
"obj_type": "rec",
"pid_type": "sub"
},
"props": {"definition": "Accelerated mass spectrometry on picked tests"},
"title": {
"en": "14c age of globigerina bulloides (itis: 45797: worms 113434) [subcomponent: tests] in sediment by picking and accelerator mass spectrometry"
},
"scheme": "BODC-PUV",
"$schema": …
```
=> subjects: added datastream for bodc

invenio_vocabularies/contrib/affiliations/schema.py
Added `Identifiers` in `AffiliationRelationSchema`
Partially fixes https://github.com/inveniosoftware/invenio-rdm-records/issues/1889
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
1. You license your contribution under the same …
=> schema: added identifiers in affiliations relation

invenio_vocabularies/config.py, invenio_vocabularies/contrib/subjects/bodc/datastreams.py, invenio_vocabularies/contrib/subjects/config.py, invenio_vocabularies/contrib/subjects/datastreams.py, invenio_vocabularies/contrib/subjects/nvs/__init__.py, invenio_vocabularies/contrib/subjects/nvs/datastreams.py, invenio_vocabularies/factories.py, tests/contrib/subjects/bodc/test_subjects_bodc_datastream.py, tests/contrib/subjects/nvs/test_subjects_nvs_datastream.py
Closes Issue https://github.com/inveniosoftware/invenio-vocabularies/issues/457
- Changed P01 collection to [P02 collection](https://vocab.nerc.ac.uk/collection/P02/current/) (contains 468 subjects)
- Updated preferred label to be used instead of alternative label in subject text
- Renamed bodc to nvs
```bash
invenio vocabularies import --vocabulary subjects:nvs --origin "http://vocab.nerc.ac.uk/collection/P02/current/?_profile=nvs&_mediatype=application/rdf+xml"
```
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
=> bodc: updated file uri & label

invenio_vocabularies/contrib/affiliations/config.py, invenio_vocabularies/contrib/funders/config.py, tests/contrib/affiliations/test_affiliations_resource.py, tests/contrib/funders/test_funders_resource.py
closes: https://github.com/inveniosoftware/invenio-vocabularies/issues/459
=> contrib: Remove redundant fields from affiliations, funders search

invenio_vocabularies/config.py, invenio_vocabularies/contrib/names/s3client.py
* (Related) Fixes zenodo/zenodo-rdm#1176
Non-blocking small improvement to avoid calling the S3 client with the default keys.
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
=> names: ORCID Public Data Sync: detect default keys

invenio_vocabularies/datastreams/readers.py
The invenio-vocabularies SPARQLReader so far doesn't allow setting a user-agent string.
This is however required to use e.g. wikidata's SPARQL endpoint as per their [policy](https://foundation.wikimedia.org/wiki/Policy:Wikimedia_Foundation_User-Agent_Policy).
After this PR is merged, it will allow setting a user agent optionally when configuring the SPARQLReader.
=> readers: allow setting user_agent in SPARQLReader

invenio_vocabularies/contrib/common/ror/datastreams.py
Invenio-jobs sends "None" in the the _since parameter as a string, and doing a datetime comparison doesn't work for None. Adding "None" here seems easier than changing the type in invenio-jobs.
**Reminder**
1. You license your contribution …
=> ror: fix handling of since being None

setup.cfg
Removed pycountry pinning as commonmeta-py does not need it anymore and the old pycountry depends on pkg-resources which are being removed.
**Frontend**
**Reminder**
2. You agree that you …
=> chore: removed pycountry pinning to <23
